---
- hosts: webserver
  become: yes
  tasks:
    - name: Install Apache
      apt: name=apache2 update_cache=yes state=present

    - name: Start Apache service
      service: name=apache2 state=started enabled=yes

    - name: Copy index.html to Apache root
      copy: src=index.html dest=/var/www/html/index.html
